---
- hosts: fuel-master
  tasks:
  - name: collect facts of fuel hosts
    fuel:
  - debug: var=hostvars
  - name: add compute node to ansible inventory
    add_host:
      name: "{{ hosts_meta[item]['ip'] }}"
      groups: fuel-compute
      ansible_user: root
      ansible_ssh_common_args: '-o StrictHostKeyChecking=No -o ProxyJump=fuel-master'
    with_items: "{{ hosts.compute }}"
- hosts: fuel-compute
  tasks:
  - name: check ssh connection
    ping:
